# Generated by Django 4.1.7 on 2023-03-09 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_size", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50, unique=True)),
                (
                    "user_symbol",
                    models.CharField(choices=[("X", "X"), ("O", "O")], max_length=1),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("col_id", models.IntegerField()),
                ("row_id", models.IntegerField()),
                (
                    "value",
                    models.CharField(
                        choices=[("", ""), ("X", "X"), ("O", "O")], max_length=1
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tic_tac_toe.game",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="current_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_player",
                to="tic_tac_toe.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_1",
                to="tic_tac_toe.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="player_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_2",
                to="tic_tac_toe.player",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to="tic_tac_toe.player",
            ),
        ),
    ]
