# Generated by Django 4.1.7 on 2023-05-26 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_size', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)])),
                ('is_finished', models.BooleanField(default=False)),
                ('draw', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_id', models.IntegerField()),
                ('row_id', models.IntegerField()),
                ('value', models.CharField(choices=[('', ''), ('X', 'X'), ('O', 'O')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tic_tac_toe.game')),
            ],
        ),
    ]
