# Generated by Django 4.1.7 on 2023-03-09 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_handler", "0001_initial"),
        ("tic_tac_toe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="current_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_player",
                to="user_handler.user",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_1",
                to="user_handler.user",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="player_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_2",
                to="user_handler.user",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to="user_handler.user",
            ),
        ),
        migrations.DeleteModel(
            name="Player",
        ),
    ]
