# Generated by Django 4.1.7 on 2023-03-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tic_tac_toe", "0002_alter_game_current_player_alter_game_player_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="current_player",
            new_name="current_turn",
        ),
    ]
