# Generated by Django 4.1.7 on 2023-03-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tic_tac_toe", "0003_rename_current_player_game_current_turn"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GameCell",
            new_name="Square",
        ),
    ]
