# Generated by Django 4.1.7 on 2023-03-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_handler', '0001_initial'),
        ('tic_tac_toe', '0005_remove_game_player_1_remove_game_player_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='user_handler.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_player', to='user_handler.user'),
        ),
    ]
